### ISSUE TITLE
New cloud shell for same session is non functional (does not accept inputs)

### ISSUE THREAD

**Issue by ShukujiNeel13** [bigdatasg/csj-kubernetes#8]
New shell session created using the Add cloud shell button on the currently active cloud shell (screenshot 1)
<img width="1437" alt="screenshot 2019-02-23 at 2 24 10 pm" src="https://user-images.githubusercontent.com/17528652/53282727-d6beae00-3776-11e9-8cfa-ad92ef82b233.png">

New shell created for the same session does not accept keyboard inputs (while the first shell does)
<img width="1414" alt="screenshot 2019-02-23 at 2 25 49 pm" src="https://user-images.githubusercontent.com/17528652/53282729-f1912280-3776-11e9-9011-7b1ac68f0e59.png">

**Comment by whatevergeek** [comment]
hi @ShukujiNeel13 , have you tried opening a third tab?
Ideally, you should be able to access from new shell tab.
This is a strange issue. Let us know if you consistently face such so we can feedback to google.

**Comment by ShukujiNeel13** [comment]
Yes, still facing the issue after restarting the cloud shell.
If this issue affects other users as well, then they will not be able to do the "Interacting with Pods" part of the Qwiklabs lab: "Orchestrating the Cloud with Kubernetes". I am curious if others are faced this issue or was it just my machine.

Again screenshots attached
---------------------
Cloud shell 1 (first cloud shell session started)
<img width="1440" alt="screenshot 2019-02-23 at 2 38 57 pm" src="https://user-images.githubusercontent.com/17528652/53282897-55b4e600-3779-11e9-9ac3-fed18276d5f8.png">
---------------------
Cloud shell 2 (new cloud shell added to session)
<img width="1436" alt="screenshot 2019-02-23 at 2 39 04 pm" src="https://user-images.githubusercontent.com/17528652/53282905-68c7b600-3779-11e9-8409-0b13ffe77e79.png">
---------------------
Cloud shell 3 (new cloud shell added to session)
<img width="1440" alt="screenshot 2019-02-23 at 2 39 12 pm" src="https://user-images.githubusercontent.com/17528652/53282914-7846ff00-3779-11e9-916d-059b35fee557.png">
---------------------

**Comment by ShukujiNeel13** [comment]
Just clarified with another person here, it seems the issue was specific to my machine.
The other person did not face the issue.
Ill try with a different browser and see if it still happens

**Comment by ShukujiNeel13** [comment]
Final update:
Does not work on the browser Safari
Works on the browser Chrome.

This issue happened when using the safari browser, but did not get reproduced in the google chrome browser (working fine).
